"""Generate a VIBECHECK.md file that AI coding assistants can consume."""

from datetime import datetime, timezone


def generate_vibecheck_md(audit: dict, llm: dict) -> str:
    """Build a markdown file instructing AI assistants to fix all found issues."""
    lines = []

    lines.append("# VIBECHECK.md")
    lines.append("")
    lines.append(f"> Auto-generated by [Vibe Audit](https://vibeaudit.com) on {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
    lines.append(f"> Repository: `{audit.get('repo_name', 'unknown')}` | Score: **{audit.get('score', '?')}/100 ({audit.get('grade', '?')})**")
    lines.append("")
    lines.append("## Instructions for AI Assistants")
    lines.append("")
    lines.append("This file contains the results of a professional code audit. When you read this file,")
    lines.append("treat each issue below as a task to fix. Work through them in priority order (critical first).")
    lines.append("For each fix, make the minimal change needed — do not refactor surrounding code.")
    lines.append("")

    # Security issues (highest priority)
    secrets = audit.get("secrets_found", [])
    sec_concerns = llm.get("security_concerns", [])

    if secrets or sec_concerns:
        lines.append("## CRITICAL: Security Issues")
        lines.append("")
        if secrets:
            lines.append("### Hardcoded Secrets Detected")
            lines.append("")
            lines.append("The following files contain hardcoded secrets that MUST be moved to environment variables:")
            lines.append("")
            for s in secrets:
                lines.append(f"- **`{s.get('file', '?')}` line {s.get('line_num', '?')}** — {s.get('pattern_type', 'Secret detected')}")
            lines.append("")
            lines.append("**Action:** Replace each hardcoded secret with an environment variable lookup")
            lines.append(f"(e.g., `os.getenv('SECRET_NAME')` for Python, `process.env.SECRET_NAME` for Node).")
            lines.append("Add the variable names to `.env.example` with placeholder values.")
            lines.append("")

        if audit.get("env_committed"):
            lines.append("### .env File in Repository")
            lines.append("")
            lines.append("A `.env` file is committed to the repository. This likely contains real credentials.")
            lines.append("")
            lines.append("**Action:**")
            lines.append("1. Add `.env` to `.gitignore`")
            lines.append("2. Create a `.env.example` with placeholder values")
            lines.append("3. Remove `.env` from git tracking: `git rm --cached .env`")
            lines.append("")

        if not audit.get("gitignore_exists"):
            lines.append("### No .gitignore")
            lines.append("")
            lines.append("**Action:** Create a `.gitignore` file appropriate for this project's language/framework.")
            lines.append("")

        for issue in audit.get("gitignore_issues", []):
            lines.append(f"- `.gitignore` issue: {issue}")
        if audit.get("gitignore_issues"):
            lines.append("")

        for concern in sec_concerns:
            sev = concern.get("severity", "medium").upper()
            lines.append(f"### [{sev}] {concern.get('issue', '')}")
            lines.append("")
            lines.append(f"**Fix:** {concern.get('fix', 'See details above.')}")
            lines.append("")

    # Architecture concerns
    arch_concerns = llm.get("architecture_concerns", [])
    if arch_concerns:
        lines.append("## Architecture Concerns")
        lines.append("")
        for i, concern in enumerate(arch_concerns, 1):
            lines.append(f"{i}. {concern}")
        lines.append("")

    # Code smells
    smells = llm.get("code_smells", [])
    if smells:
        lines.append("## Code Smells")
        lines.append("")
        for smell in smells:
            sev = smell.get("severity", "medium").upper()
            lines.append(f"- **[{sev}] `{smell.get('file', '?')}`**: {smell.get('issue', '')}")
        lines.append("")

    # Priority fixes (the main action list)
    fixes = llm.get("priority_fixes", [])
    if fixes:
        lines.append("## Priority Fix List")
        lines.append("")
        lines.append("Work through these in order. Each fix includes the estimated effort.")
        lines.append("")
        for i, fix in enumerate(fixes, 1):
            sev = fix.get("severity", "medium").upper()
            effort = fix.get("effort", "?")
            lines.append(f"### {i}. [{sev}] {fix.get('title', '')} (~{effort})")
            lines.append("")
            if fix.get("file"):
                lines.append(f"**File:** `{fix['file']}`")
                lines.append("")
            lines.append(fix.get("description", ""))
            lines.append("")
            if fix.get("fix_snippet"):
                lines.append("**Suggested fix:**")
                lines.append("```")
                lines.append(fix["fix_snippet"])
                lines.append("```")
                lines.append("")

    # Missing basics
    missing = []
    if not audit.get("has_tests"):
        missing.append(("Add Tests", "This project has no test files. Create a test suite covering the core functionality. Start with the main entry point and critical business logic."))
    if not audit.get("has_ci"):
        missing.append(("Set Up CI/CD", "No CI/CD configuration found. Add a GitHub Actions workflow (or equivalent) that runs linting and tests on every push."))
    if not audit.get("has_linting"):
        missing.append(("Add Linting", "No linter configured. Add a linting configuration appropriate for this project's language (e.g., ruff/black for Python, eslint/biome for JS/TS)."))
    if not audit.get("has_readme"):
        missing.append(("Add README", "No README file found. Create a README.md with: project description, setup instructions, usage examples, and contribution guidelines."))

    if missing:
        lines.append("## Missing Best Practices")
        lines.append("")
        for title, desc in missing:
            lines.append(f"### {title}")
            lines.append("")
            lines.append(desc)
            lines.append("")

    # Summary stats for context
    lines.append("---")
    lines.append("")
    lines.append("## Audit Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Score | {audit.get('score', '?')}/100 ({audit.get('grade', '?')}) |")
    lines.append(f"| Language | {audit.get('primary_language', '?')} |")
    lines.append(f"| Files | {audit.get('total_files', '?')} |")
    lines.append(f"| LOC | {audit.get('total_loc', '?'):,} |")
    lines.append(f"| Dependencies | {audit.get('dependency_count', '?')} |")
    lines.append(f"| Secrets Found | {len(secrets)} |")
    lines.append(f"| Tests | {'Yes' if audit.get('has_tests') else 'No'} |")
    lines.append(f"| CI/CD | {'Yes' if audit.get('has_ci') else 'No'} |")
    lines.append(f"| Linting | {'Yes' if audit.get('has_linting') else 'No'} |")
    lines.append("")

    if llm.get("overall_assessment"):
        lines.append("## Overall Assessment")
        lines.append("")
        lines.append(llm["overall_assessment"])
        lines.append("")

    return "\n".join(lines)
